DROP TABLE TEMPLATES;
DROP TABLE TEMPLATE_ACCESS_LIST;
DROP TABLE TEMPLATE_ACCOUNTS;
DROP TABLE TEMPLATE_USERS;
DROP table template_course_delegates;
DROP TABLE template_groups;

DROP sequence TEMPLATES_SQ;
DROP sequence TEMPLATES_ACCESS_SQ;
DROP sequence TEMPLATES_COURSE_DELEGATES_SQ;

CREATE TABLE TEMPLATES (
    "TEMPLATE_ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "TERM" NVARCHAR2(200),
    "TITLE" NVARCHAR2(200),
    "CANVAS_COURSE_ID" NUMBER(11) NOT NULL
    "DATE_CREATED" TIMESTAMP DEFAULT SYSDATE NOT NULL
)
;
CREATE TABLE TEMPLATE_ACCOUNTS (
    "SIS_ACCOUNT_ID" NVARCHAR2(20) NOT NULL PRIMARY KEY,
    "ACCOUNT_NAME" NVARCHAR2(50),
    "CAN_USE_WIZARD" NVARCHAR2(1)
)
;
CREATE TABLE TEMPLATE_USERS (
    "USER_ID" NVARCHAR2(20) NOT NULL PRIMARY KEY,
    "SIS_ACCOUNT_ID" NVARCHAR2(20),
    "CAN_MANAGE_TEMPLATES" NVARCHAR2(1),
    "CAN_BULK_CREATE_COURSES" NVARCHAR2(1),
    "CAN_MANAGE_USERS" NVARCHAR2(1),
    "DATE_ADDED" TIMESTAMP DEFAULT SYSDATE NOT NULL
)
;
CREATE TABLE TEMPLATE_GROUPS (
    "GROUP_ID" NVARCHAR2(20) NOT NULL PRIMARY KEY,
    "SIS_ACCOUNT_ID" NVARCHAR2(20),
    "CAN_MANAGE_TEMPLATES" NVARCHAR2(1),
    "CAN_BULK_CREATE_COURSES" NVARCHAR2(1),
    "DATE_ADDED" TIMESTAMP DEFAULT SYSDATE NOT NULL
)
;
CREATE TABLE TEMPLATE_ACCESS_LIST (
    "ACCESS_ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "SIS_ACCOUNT_ID" NVARCHAR2(20) NOT NULL REFERENCES "TEMPLATE_ACCOUNTS" ("SIS_ACCOUNT_ID") DEFERRABLE INITIALLY DEFERRED,
    "TEMPLATE_ID" NUMBER(11) NOT NULL REFERENCES "TEMPLATES" ("TEMPLATE_ID") DEFERRABLE INITIALLY DEFERRED,
    "USER_ID" NVARCHAR2(20) NOT NULL REFERENCES "TEMPLATE_USERS" ("USER_ID") DEFERRABLE INITIALLY DEFERRED,
    "DATE_GRANTED" TIMESTAMP DEFAULT SYSDATE NOT NULL
)
;
CREATE TABLE TEMPLATE_COURSE_DELEGATES (
    "DELEGATE_ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "COURSE_INSTANCE_ID" NVARCHAR2(20),
    "DELEGATE_USER_ID" NVARCHAR2(20),
    "DATE_ADDED" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL
)
;

CREATE SEQUENCE TEMPLATES_SQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE TEMPLATES_ACCESS_SQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE TEMPLATES_COURSE_DELEGATES_SQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

-- Insert some dummy data 
Insert into TEMPLATE_ACCOUNTS (SIS_ACCOUNT_ID,ACCOUNT_NAME,CAN_USE_WIZARD) values ('colgsas','Harvard College','Y');
Insert into TEMPLATE_ACCOUNTS (SIS_ACCOUNT_ID,ACCOUNT_NAME,CAN_USE_WIZARD) values ('ext','Harvard Extension School','Y');
Insert into TEMPLATE_ACCOUNTS (SIS_ACCOUNT_ID,ACCOUNT_NAME,CAN_USE_WIZARD) values ('hds','Harvard Design School','Y');
Insert into TEMPLATE_ACCOUNTS (SIS_ACCOUNT_ID,ACCOUNT_NAME,CAN_USE_WIZARD) values ('gse','gse','Y');
Insert into TEMPLATE_ACCOUNTS (SIS_ACCOUNT_ID,ACCOUNT_NAME,CAN_USE_WIZARD) values ('hls-berkman','hls-berkman','N');