    terms_map = {0 : "summer",
        1 : "fall",
        2 : "spring",
        4 : "full-year",
        5 : "winter",
        6 : "fall-1",
        7 : "fall-2",
        8 : "spring-1",
        9 : "spring-2",
        10 : "summer-1",
        11 : "summer-2",
        12 : "fall-winter",
        13 : "winter-spring",
        14 : "fall-saturday",
        15 : "spring-saturday",
        16 : "june",
        17 : "july",
        18 : "august",
    }