# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-05 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualtrics_link', '0002_add_acceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualtricsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_id', models.CharField(max_length=32)),
                ('qualtrics_id', models.CharField(max_length=32)),
                ('manually_updated', models.BooleanField()),
            ],
            options={
                'db_table': 'qualtrics_user',
            },
        )
    ]
