# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualtrics_link', '0003_auto_20180105_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualtricsuser',
            name='division',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qualtricsuser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='qualtricsuser',
            name='user_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='acceptance_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='user_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
