# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-25 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualtrics_link', '0004_auto_20190508_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualtricsuser',
            old_name='division',
            new_name='qualtrics_division',
        ),
        migrations.RenameField(
            model_name='qualtricsuser',
            old_name='user_type',
            new_name='qualtrics_user_type',
        ),
    ]
