# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualtrics_link', '0005_auto_20190925_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualtricsuser',
            name='iam_division',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qualtricsuser',
            name='iam_user_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qualtricsuser',
            name='lpp_division',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qualtricsuser',
            name='lpp_user_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
